#!/bin/bash

screenshot="/tmp/Screenshot $(date "+%Y.%m.%d at %H:%M").png"
grim "${screenshot}"
wl-copy < "${screenshot}"
notify-send -i "${screenshot}" -u normal -a screenshot "Screenshot saved in clipboard"
